// import { Vehicle, PickupLocation } from '../types';

// export const VEHICLES: Vehicle[] = [
//   {
//     id: '1',
//     name: 'Scooty',
//     type: 'bike',
//     image: require('../../assets/vehicles/bike.jpg'),
//     eta: '3 mins',
//     dropBy: 'Drop 3:58 pm',
//     baseFare: 85,
//     subtitle: 'Quick and affordable',
//     capacity: 1,
//   },
//   {
//     id: '1b',
//     name: 'Bike',
//     type: 'bike',
//     image: require('../../assets/vehicles/bike.jpg'),
//     eta: '2 mins',
//     dropBy: 'Drop 3:55 pm',
//     baseFare: 90,
//     subtitle: 'Fastest through traffic',
//     capacity: 1,
//   },
//   {
//     id: '2',
//     name: 'Auto Lite',
//     type: 'auto',
//     image: require('../../assets/vehicles/auto.jpg'),
//     eta: '3 mins',
//     dropBy: 'Drop 3:59 pm',
//     baseFare: 100,
//     badge: 'Cheaper',
//   },
//   {
//     id: '3',
//     name: 'Auto',
//     type: 'auto',
//     image: require('../../assets/vehicles/auto.jpg'),
//     eta: '3 mins',
//     dropBy: 'Drop 3:59 pm',
//     baseFare: 105,
//     subtitle: 'Hassle-free Auto rides',
//     capacity: 3,
//   },
//   {
//     id: '4',
//     name: 'Auto Priority',
//     type: 'auto',
//     image: require('../../assets/vehicles/auto.jpg'),
//     eta: '3 mins',
//     dropBy: 'Drop 3:59 pm',
//     baseFare: 144,
//     badge: 'Quickest',
//   },
//   {
//     id: '6',
//     name: 'Cab Non-AC',
//     type: 'cab',
//     image: require('../../assets/vehicles/cab.jpg'),
//     eta: '4 mins',
//     dropBy: 'Drop 4:02 pm',
//     baseFare: 155,
//     subtitle: 'Budget friendly cab',
//     capacity: 4,
//   },
//   {
//     id: '5',
//     name: 'Cab AC',
//     type: 'cab',
//     image: require('../../assets/vehicles/cab.jpg'),
//     eta: '3 mins',
//     dropBy: 'Drop 3:59 pm',
//     baseFare: 171,
//   },
// ];

// export const PICKUP_OPTIONS = (baseFare: number): PickupLocation[] => [
//   {
//     id: 'p1',
//     title: 'Nearby Pickup',
//     subtitle: 'Walk & Save',
//     distance: '150m walking',
//     fare: baseFare - 20, // Discount for walking
//     latitude: 17.385044,
//     longitude: 78.486671,
//   },
//   {
//     id: 'p2',
//     title: 'Current Location',
//     subtitle: 'Your location',
//     fare: baseFare,
//     latitude: 17.3850,
//     longitude: 78.4867,
//     isCurrent: true,
//   },
// ];

// export const CANCEL_REASONS = [
//   'Driver taking too long',
//   'Found another ride',
//   'Wrong destination selected',
//   'Fare too high',
//   'Changed my plans',
//   'Other',
// ];
